### ISSUE TITLE
Code Loading Problems

### ISSUE THREAD

**Issue by Jaysoooon** [jchabin/cars#4]
It's been happening infrequently for about 2 weeks now, but now every time my friends and I want to start a game none of us can get a code to generate, it just says 'Loading'. My friend thinks that it may have generated all the code combinations it can, since we've been playing very competitively and frequently for the last couple months (It's going extremely well, and your game has been played internationally very smoothly). Just wondering if maybe there is an update needed or something else. 

p.s. I'm really new to coding and don't really understand much.

**Comment by jchabin** [comment]
I think this was actually due to server issues, which I have fixed in https://github.com/jchabin/cars/commit/2b239916da24f05502bcbdcc4e008167420addce - but I'm also aware of the possibility of running out of codes, which I went ahead and fixed in https://github.com/jchabin/cars/commit/303f83ac0ad53175be000e7af9d563ec5c200586.
